### ISSUE TITLE
NNUE question

### ISSUE THREAD

**Issue by GrahamCCRL** [jasper-sinclair/kobra#3]
Are you using a 'borrowed' NNUE or is Kobra using an original one?

Graham (CCRL)

**Comment by jasper-sinclair** [comment]
Hi Graham,

Thanks for your interest in Kobra.

Kobra source code and it's NNUE evaluation net are 100% original.  Kobra_1.0.nnue was created from the many millions of self-play games created during development and testing. No other data was used.

For more info, see src/nnue.md.

**Comment by GrahamCCRL** [comment]
Excellent.
I've put it into my Amateur Series.

**Comment by jasper-sinclair** [comment]
Awesome! 
Sounds like fun. Thanks.

**Comment by jasper-sinclair** [comment]
Hi Graham,


 

Thanks very much for hosting this tournament.  I watched one of the Kobra games today and noticed that you were using
Kobra 1.0 which has a serious bug making it play much weaker than normal...(with increment time controls, it uses increment only).

 

2 weeks ago I released a fix: Kobra 1.0a ...see https://github.com/jasper-sinclair/kobra/releases/tag/1.0a.

This is in fact the version that appears in your CCRL 40/15 rating list https://computerchess.org.uk/ccrl/4040/ so I assumed

of course you were aware of the update.

 

Is it possible to use this updated release for the rest of the tournament?

 

In any event, thanks again for inviting Kobra to your Amateur competition!


Best Regards,

Jasper

 

Sent: Wednesday, March 13, 2024 at 3:03 PM

**Comment by GrahamCCRL** [comment]
I'll update shoertly. :-)

**Comment by GrahamCCRL** [comment]
1.0a is replaying the first few games now.

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Mon, Apr 29, 2024 at 11:03 AM
Subject: 108th Amateur Series Division 7
To: Krasimir Topchiyski ***@***.***>, ***@***.***>,
Duhamel Patrice ***@***.***>, Richard Pijl ***@***.***>,
***@***.***>, WillChing01/Pingu <
***@***.***>


*108TH AMATEUR SERIES (Division 7)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU (64-bit where available)

*The top engine will be promoted and the bottom engine will be relegated.
Any other changes of division will be at my discretion and may not
necessarily involve playoff matches.*

*Participants*

4ku 4.0 64-bit *(relegated)*
Bagatur 4.1a 64-bit *(relegated)*
Francesca MAD 0.32 64-bit
Ynode 0133 64-bit
Cheese 3.2.1 64-bit
Kobra 1.1 64-bit *(promoted)*
ice4 4.0 64-bit *(relegated)*
tomitankChess 5.1 64-bit
The Baron 3.45 64-bit
OliThink 5.10.5 64-bit
Clovis III 64-bit
Inanis 1.2.0 64-bit *(promoted)*
Lambergar 0.5.2 64-bit *(promoted)*
Pingu 3.0.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Sun, May 19, 2024 at 11:25 PM
Subject: New Tournament
To: Charles Roberson ***@***.***>, ***@***.***>, <
***@***.***>, ***@***.***>


*THE OVERPOWERING FRAGRANCE*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 36 rounds
All engines 1CPU


*Participants*

Simbelmyne 1.7.0 64-bit
OliThink 5.10.5 64-bit
Clovis III 64-bit
Ares 3.0.3 64-bit
Cheers 0.3.0 64-bit
Nemo 1.0.1 64-bit
Dumb 2.1 64-bit
Onno 1.2.70 64-bit
Seawall 20231015 64-bit
Belette 3.0.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16071

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16071
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Sun, May 19, 2024 at 11:36 PM
Subject: New Tournament
To: Amir Ban ***@***.***>, Fons Bluemers ***@***.***>,
Andres Valverde ***@***.***>, Duhamel Patrice <
***@***.***>, Richard Pijl ***@***.***>


*STRIKE OF THE KOBRA*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 36 rounds
All engines 1CPU


*Participants*

Vengeance 3.0.0 64-bit
Sirius 6.0 64-bit
ice4 4.0 64-bit
Deep Junior Yokohama 64-bit
Dirty CUCUMBER 64-bit
Crafty 25.6 64-bit
Kobra 1.1 64-bit
Cheese 3.2.1 64-bit
The Baron 3.45 64-bit
smol.cs 1.61 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16064

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16064
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Mon, Jun 10, 2024 at 2:37 PM
Subject: 109th Amateur Series Division 7
To: Krasimir Topchiyski ***@***.***>, <
***@***.***>, ***@***.***>,
***@***.***>, Duhamel Patrice ***@***.***>, Richard
Pijl ***@***.***>


*109TH AMATEUR SERIES (Division 7)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU (64-bit where available)

*The top engine will be promoted and the bottom engine will be relegated.
Any other changes of division will be at my discretion and may not
necessarily involve playoff matches.*

*Participants*

Simbelmyne 1.8.0 64-bit *(promoted)*
Odonata 0.9.0 64-bit *(promoted)*
Kobra 1.2 64-bit
Bagatur 5.0 HCE 64-bit
Ceibo 1.0 64-bit *(relegated)*
Sirius 6.0 64-bit
Francesca MAD 0.32 64-bit
Lambergar 0.5.2 64-bit
Vengeance 3.0.0 64-bit *(relegated)*
Cheese 3.2.1 64-bit
ice4 4.0 64-bit
tomitankChess 5.1 64-bit
The Baron 3.45 64-bit
Cheers 0.3.0 64-bit *(promoted)*


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16069

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16069
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Thu, Jul 4, 2024 at 10:16 PM
Subject: New Tournament
To: Alex Brunetti ***@***.***>, Krasimir Topchiyski <
***@***.***>, Tom Hyer ***@***.***>


*ROCKY FLIGHT*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds
All engines 1CPU


*Participants*

Pedantic 1.1.0 64-bit
Zangdar 2.29.01 64-bit
Jet 1.2 64-bit
Monty 1.0.0 64-bit
Ynode 0134 64-bit
Protej 0.6.6 64-bit
Bagatur 5.1 64-bit
Mida 2.3.1 64-bit
Odonata 0.9.0 64-bit
Roc 2.0 64-bit
Kobra 1.2 64-bit
Princhess 0.17.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16071

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16071
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Thu, Jul 18, 2024 at 11:59 PM
Subject: 110th Amateur Series Division 7
To: Andres Manzanares ***@***.***>, Vasik Rajlich <
***@***.***>, Duhamel Patrice ***@***.***>


*110TH AMATEUR SERIES (Division 7)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
IM_4mvs.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU (64-bit where available)

*The top engine will be promoted and the bottom engine will be relegated.
Any other changes of division will be at my discretion and may not
necessarily involve playoff matches.*

*Participants*

Atlas 4.35 64-bit *(relegated)*
GOOB 1.8.9 64-bit
Elixir 2.0 64-bit *(promoted)*
Kobra 1.2 64-bit
Integral v2 64-bit *(relegated)*
4ku 4.0 64-bit *(relegated)*
Rybka 2.3.2a 64-bit *(fill-in for Patricia as the latest version is too
strong for D7)*
Monty 1.0.0 64-bit
Ceibo 1.0 64-bit
Vengeance 3.0.0 64-bit
ice4 4.0 64-bit
Cheese 3.2.1 64-bit
tomitankChess 5.1 64-bit
Inanis 1.3.0 64-bit *(promoted)*


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16069

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16069
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*SISTER OF THE CLEANING LADY*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds
All engines 1CPU


*Participants*

bitbit 1.2 64-bit
Kobra 1.2 64-bit
Cadie 1.8 64-bit
Inanis 1.4.0 64-bit
Wahoo 4.0 64-bit
SmarThink 1.98 64-bit
Simbelmyne 1.9.0 64-bit
4ku 5.0 64-bit
Calvin 4.0.2 64-bit
Elixir 2.0 64-bit
Ares 3.0.3 64-bit
Heimdall 0.4 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16071

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16071
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*CALVIN PLAYS DIRTY*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
6 cycles 42 rounds
All engines 1CPU


*Participants*

Kobra 1.2 64-bit
Simbelmyne 1.9.0 64-bit
4ku 5.0 64-bit
Calvin 4.0.2 64-bit
ice4 5.0 64-bit
Francesca MAD 0.32 64-bit
Monty 1.0.0 64-bit
Dirty Duna 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16067

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16067
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by jasper-sinclair** [comment]
Hello Graham,
Thanks alot for the email notification.
Unfortunately the link you specify  below (https://ccrl.live/16067) is instantly rerouted to https://ccrl.live/16066
some unnamed competition with very strong engines in which Kobra is not a participant.

Best Regards-
Jasper

**Comment by AlexBrunetti** [comment]
> Hello Graham, Thanks alot for the email notification. Unfortunately the link you specify  below (https://ccrl.live/16067) is instantly rerouted to https://ccrl.live/16066 some unnamed competition with very strong engines in which Kobra is not a participant.
> 
> Best Regards- Jasper

The tournament is already finished,
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?t=17019

Alex

**Comment by jasper-sinclair** [comment]
Oh I see...thanks.👍

**Comment by GrahamCCRL** [comment]
---------- Forwarded message ---------
From: Graham Banks ***@***.***>
Date: Sat, Aug 31, 2024 at 5:28 PM
Subject: 111th Amateur Series Division 7
To: Tom Hyer ***@***.***>, ***@***.***>


*111TH AMATEUR SERIES (Division 7)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU

*The top engine will be promoted and the bottom engine will be relegated.
Any other changes of division will be at my discretion and may not
necessarily involve playoff matches.*

*Participants*

bitbit 1.2 64-bit *(relegated)*
Kobra 1.2 64-bit
Wahoo 4.0 64-bit *(relegated)*
4ku 5.0 64-bit
Ceibo 1.0 64-bit
Elixir 2.0 64-bit
Francesca MAD 0.32 64-bit *(promoted)*
Vengeance 3.0.0 64-bit *(promoted)*
Roc 2.0.3 64-bit *(relegated)*
Calvin 4.0.2 64-bit *(promoted)*
Inanis 1.4.0 64-bit
Monty 1.0.0 64-bit
tomitankChess 5.1 64-bit
ice4 5.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16065

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16065
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*THE FINAL FRONTIER*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds
All engines 1CPU


*Participants*

Sirius 7.0 64-bit
Zangdar 2.30 64-bit
Ares 5.2.2 64-bit
Princhess 0.18.0 64-bit
Heimdall 1.0 64-bit
Protej 0.6.7 64-bit
Mida 2.3.1 64-bit
Lambergar 0.6.0 64-bit
Cadie 1.8 64-bit
Roc 2.0.3 64-bit
Calvin 4.1.0 64-bit
Kobra 1.2 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16073

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16073
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*112TH AMATEUR SERIES (Division 7)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU

*The top engine will be promoted and the bottom engine will be relegated.
Any other changes of division will be at my discretion and may not
necessarily involve playoff matches.*

*Participants*

Lambergar 0.6.0 64-bit *(relegated)*
Mida 2.3.1 64-bit *(relegated)*
Atlas 4.35 64-bit *(relegated)*
Orion 1.0 64-bit *(relegated)*
Lynx 1.7.0 64-bit *(promoted)*
Roc 2.0.3 64-bit
Heimdall 1.0.0 64-bit
Kobra 1.2 64-bit
Cheers 1.0.0 64-bit *(dav)*
Wahoo 4.0 64-bit
Arcanum 2.3.1 64-bit *(promoted)*
Pingu 4.0.0 64-bit *(promoted)*
Dirty Duna 64-bit *(promoted)*
Ares *(new version)*


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16065

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16065
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
*113TH AMATEUR SERIES (Division 7)*

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds
All engines 1CPU

*The top engine will be promoted and the bottom engine will be relegated.
Any other changes of division will be at my discretion and may not
necessarily involve playoff matches.*

*Participants*

Simbelmyne 1.10.0 64-bit
Lynx 1.7.0 64-bit
Mida 2.3.1 64-bit
Roc 2.0.3 64-bit
Arcanum 2.3.1 64-bit
Orion 1.0 64-bit
Lambergar 0.6.0 64-bit
Perseus 0.9-alpha 64-bit *(promoted)*
bitbit 1.2 64-bit *(relegated)*
Kobra 1.2 64-bit
Wahoo 4.0 64-bit
EveAnn 2.1 64-bit *(promoted)*
ice4 5.0 64-bit *(promoted)*
Pingu 4.0.0 64-bit


Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16064

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your
computer, you can watch the games live move by move. You'll also be able to
chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discuss ... p?id=42959
<http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959>
Host - GrahamCCRL.dyndns.org Port - 16064
Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
FROM DARKNESS INTO LIGHT

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 44 rounds

Cadie 2.0 64-bit
Arcanum 2.4 64-bit
WhiteCore 0.2 64-bit
Nirvanachess 2.5 64-bit
Mida 2.3.1 64-bit
Roc 2.0.4 64-bit
Perseus 0.9-alpha 64-bit
Lynx 1.7.0 64-bit
Orion 1.0 64-bit
Lambergar 0.6.0 64-bit
Kobra 1.2 64-bit
EveAnn 2.1 64-bit

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16071

**Comment by GrahamCCRL** [comment]
114TH AMATEUR SERIES (Division 7)

AMD Ryzen 5950x
ChessGUI
256mb hash each where possible
6 piece tablebases
Ponder off
GBSelect2024.cgb book
12 minutes with 8 second increments.
4 cycles 52 rounds

Arcanum 2.4 64-bit
Protej 0.6.7 64-bit (relegated)
Jet 1.2 64-bit
WhiteCore 0.2 64-bit (relegated)
Sturddle 2.01 64-bit (new)
ChessBrainVB 4.02 (relegated)
Lynx 1.8.0 64-bit
ChandraChess 2.0 64-bit (promoted)
Mida 2.3.1 64-bit
Atlas 4.35 64-bit (relegated)
Myrddin 0.92 64-bit (promoted)
Lambergar 0.6.0 64-bit
bitbit 1.2 64-bit
Kobra 1.2 64-bit

Web based link for live viewing (courtesy of Jay - Berserk author).
https://ccrl.live/16072
